### ISSUE TITLE
Adding rules for Igbo

### ISSUE THREAD

**Issue by chrisemezue** [masakhane-io/masakhane-preprocessing#1]
Language: Igbo
[Lang code](https://en.wikipedia.org/wiki/IETF_language_tag): ig
> Don't worry about language codes so much if you do not know. We will gladly take care of that.

`allowed_symbols`: ['.-]
`diacritics`: True
Example sentene to test: `Dịka● ndọrọndọrọọchịchị maka ntuliaka ọkwa Gọvanọ Anambra steeti si na-aga nke afọ 2021, ndị nọ.`

**Comment by bonaventuredossou** [comment]
Language: Fon
Lang code: fon

allowed_symbols: ['à', 'á', 'è', 'é', 'ì', 'í', 'î', 'ï', 'ó', 'ù', 'ú', 'ā', 'ă', 'ē', 'ĕ', 'ŏ', 'ū', 'ŭ', 'ɔ', 'ɖ', 'ò', 'ε', 'έ', 'ɔ̀', 'ɔ̆', 'ὲ', 'ɔ́', 'ĭ', 'ɛ̆', 'ɛ̃']
diacritics: True
