### ISSUE TITLE
Pidgin corpus

### ISSUE THREAD

**Issue by sam4rano** [masakhane-io/masakhane-preprocessing#14]
credits: https://github.com/keleog/PidginUNMT

[pidgin_corpus.txt](https://github.com/masakhane-io/masakhane-preprocessing/files/7962836/pidgin_corpus.txt)

**Comment by chrisemezue** [comment]
Thank you @sam4rano 

I have created [this](https://github.com/masakhane-io/masakhane-preprocessing/tree/main/african-stopwords#extracting-from-monolingual-corpus) to help you extract some potential stopwords from the corpus.

Simply run
```python extract.py --file=pidgin_corpus.txt --output=pidgin_freq.txt
```

Your output file `pidgin_freq.txt` will be words with their frequency sorted inn decreasing order. Review the file.
If after review, you conclude that maybe words with frequency more than `X` are most likely to be stopwords, then run
```python extract.py --file=pidgin_corpus.txt --output=pcm.txt --freq=X
```
This will create a file `pcm.txt` with the words which have frequency >= `X`. You can now edit this file and send it in a pull request.

**Comment by chrisemezue** [comment]
If you have any questions let me know
