### ISSUE TITLE
Adding rules for Fon

### ISSUE THREAD

**Issue by bonaventuredossou** [masakhane-io/masakhane-preprocessing#2]
Language: Fon
Lang code: fon

allowed_symbols: ['à', 'á', 'è', 'é', 'ì', 'í', 'î', 'ï', 'ó', 'ù', 'ú', 'ā', 'ă', 'ē', 'ĕ', 'ŏ', 'ū', 'ŭ', 'ɔ', 'ɖ', 'ò', 'ε', 'έ', 'ɔ̀', 'ɔ̆', 'ὲ', 'ɔ́', 'ĭ', 'ɛ̆', 'ɛ̃']
diacritics: True

**Comment by chrisemezue** [comment]
Please @bonaventuredossou  can you give an example sentence to test?

**Comment by chrisemezue** [comment]
> Please @bonaventuredossou can you give an example sentence to test?

Never mind. I found something

`ði ɔ enyi winnya ɖu nɔ mya nukún nú mǐ hú nǔ bǐ ɔ mǐ sixu nugbǒmaɖɔ dó mɔ nǔ ɖò dandan é ɖé`

**Comment by chrisemezue** [comment]
Are there special linguistic considerations for Fon language besides diacritics? @bonaventuredossou

**Comment by bonaventuredossou** [comment]
This will be more on the speech part. Except that the diacritics are the ones making huge difference on written communication form

**Comment by chrisemezue** [comment]
All right.
Thanks a lot. Fon has been added! You can check that the preprocessor works correctly. 
If you find some issues, feel free to re-open this issue or create another one.
